language: bash
services: docker

env:
  - VERSION=7.1 VARIANT= EXTRA_TAG=latest CLI_TAG=7.1-cli
  - VERSION=7.0 VARIANT= CLI_TAG=7.0-cli
  - VERSION=5.6 VARIANT= CLI_TAG=5.6-cli
  - VERSION=5.5 VARIANT= CLI_TAG=5.5-cli

before_script:
  - cd "$VERSION"
  - IMAGE="mileschou/swoole"
  - IMAGE_VERSION="${VERSION}${VARIANT:+-$VARIANT}"
  - IMAGE_VERSION="${IMAGE_VERSION//'/'/-}"
  - IMAGE_NAME="$IMAGE:$IMAGE_VERSION"
  - echo "$IMAGE_NAME"

script:
  - docker build -t "$IMAGE_NAME" "${VARIANT:-.}"
  - if [ "$EXTRA_TAG" != "" ]; then docker tag "$IMAGE_NAME" "$IMAGE:$EXTRA_TAG" ; fi
  - if [ "$CLI_TAG" != "" ]; then docker tag "$IMAGE_NAME" "$IMAGE:$CLI_TAG" ; fi
  - docker images
  - docker run -i -t --rm $IMAGE_NAME php -m
  - docker login -u $DOCKER_HUB_USERNAME -p $DOCKER_HUB_PASSWORD
  - docker push $IMAGE
