language: bash
services: docker

branches:
  only:
    - master

env:
  - VERSION=7.3
  - VERSION=7.2
  - VERSION=7.1
  - VERSION=7.0
  - VERSION=5.6
  - VERSION=5.5

script:
  - docker build -t swoole:${VERSION} ${VERSION}
  - docker run -i -t --rm swoole:${VERSION} php -m
